name: jumpstart-demo
recipe: drupal8
# proxy:
#   solr:
#     - solr.se3blt.sws:8983
config:
  webroot: docroot
  xdebug: true
  php: '7.2'
  drush: composer
services:
  appserver:
    ssl: true
    extras:
      - "apt-get update"
      - "ln -s /app/vendor/bin/blt /usr/bin/blt"
  database:
    type: mysql:5.7
  # solr:
  #   type: solr:5.5
  #   portforward: true
  #   core: project
  #   config:
  #     conf: solrconf
  # memcache:
  #   type: memcached:1.5
  #   mem: 128
  #   portforward: true
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  git:
    service: appserver
